"""init tables

Revision ID: 8669f06161df
Revises: 
Create Date: 2026-01-30 10:54:06.922861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8669f06161df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('truck_no', sa.String(length=50), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=4), server_default='0.3000', nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('periods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'locked', name='period_status'), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('admin_fee', 'insurance', 'fuel', 'toll', 'repair', 'penalty', 'other', name='expense_type'), nullable=False),
    sa.Column('charged_to', sa.Enum('driver', 'company', name='charged_to'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(charged_to <> 'driver') OR (driver_id IS NOT NULL)", name='ck_expenses_driver_required_when_charged_to_driver'),
    sa.CheckConstraint("(type <> 'other') OR (note IS NOT NULL AND length(trim(note)) > 0)", name='ck_expenses_note_required_when_type_other'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_driver_id'), 'expenses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_expenses_period_id'), 'expenses', ['period_id'], unique=False)
    op.create_table('loads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('load_number', sa.String(length=80), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_location', sa.String(length=30), nullable=False),
    sa.Column('delivery_location', sa.String(length=30), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_gross', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('company_gross', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('load_number')
    )
    op.create_index(op.f('ix_loads_driver_id'), 'loads', ['driver_id'], unique=False)
    op.create_index(op.f('ix_loads_period_id'), 'loads', ['period_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'driver', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_loads_period_id'), table_name='loads')
    op.drop_index(op.f('ix_loads_driver_id'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_expenses_period_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_driver_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('periods')
    op.drop_table('drivers')
    # ### end Alembic commands ###
